### ISSUE TITLE
JGit Maven Repository Link in Pom.xml

### ISSUE THREAD

**Issue by carlsonp** [pridkett/gitminer#23]
http://download.eclipse.org/jgit/maven

The link in the Pom.xml file for JGit Maven seems to be broken.  This may be helpful:

http://wiki.eclipse.org/EGit/Contributor_Guide#Maven_Build_Sequence

**Comment by pridkett** [comment]
How are you trying to compile the package. When I compile it using the instructions in README.md it works just fine on my system. Can you post the error that you get after running the following command?

```
mvn clean compile package assembly:single
```

**Comment by carlsonp** [comment]
Thanks that fixed it.  I'm guessing it was related to issue #24.  Cheers.
